artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/file/d/1Qf8n_BzAf7tfrNqK2QGPhvePmoLYXp6m/view?usp=sharing
  local_data_file: artifacts/data_ingestion/mlops_data.zip
  unzip_dir: artifacts/data_ingestion